---
- name: Check kafka tar file existence
  stat:
    path: "{{ download_dir }}/kafka_{{ scala_version }}-{{ version }}.tgz"
  register: kafka_tar

- name: Download kafka from {{ download_url }}
  get_url:
    url: "{{ download_url }}"
    dest: "{{ download_dir }}//kafka_{{ scala_version }}-{{ version }}.tgz"
    owner: kafka
    group: kafka
    timeout: 600
  become: yes
  when: not kafka_tar.stat.exists