---
- name: "Extract files to {{ install_dir }}"
  unarchive:
    src: "{{ download_dir }}/kafka_{{ scala_version }}-{{ version }}.tgz"
    dest: "{{ install_dir }}"
    keep_newer: yes
    extra_opts: [--strip-components=1]
    mode: "0744"
    owner: kafka
    group: kafka
    remote_src: yes
  become: yes


- name: Copy systemd environment file
  template:
    src: kafka.env.j2
    dest: /etc/systemd/system/kafka.env
  become: yes
  notify:
    - Enable kafka
    - Reload systemctl
    - Restart kafka

- name: Copy systemd script
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
  become: yes
  notify:
    - Enable kafka
    - Reload systemctl
    - Restart kafka

- name: Configure kafka broker
  template:
    src: server.properties.j2
    dest: "{{ install_dir }}/config/server.properties"
    owner: kafka
    group: kafka
  become: yes
  notify:
    - Restart kafka